syntax = "proto3";

package voice_channel.v1;

import "voice_channel/v1/events.proto";
import "voice_channel/v1/requests.proto";

message VoiceChannelEventEnvelope {
  oneof payload {
    VoiceChannelUserJoinedEvent user_joined_event = 1;
    VoiceChannelUserLeftEvent user_left_event = 2;
    VoiceChannelCreatedEvent channel_created_event = 3;
    VoiceChannelDeletedEvent channel_deleted_event = 4;
    BotVoiceChannelNameChangedEvent name_changed = 5;
    BotVoiceChannelNameChangeRejectedEvent name_change_reject = 6;
    BotVoiceChannelLimitChangedEvent limit_changed = 7;
    VoiceChannelThrottleAvailableEvent throttle_available = 8;
  }
}

message VoiceChannelRequestEnvelope {
  oneof payload {
    CreateVoiceChannelRequest create_channel_request = 1;
    DeleteVoiceChannelRequest delete_channel_request = 2;
    UpdateVoiceChannelRequest update_channel_request = 3;
    ChangeVoiceChannelNameRequest name_change_request = 4;
    ChangeVoiceChannelLimitRequest limit_change_request = 5;
  }
}