syntax = "proto3";

package voice_channel.v1;

import "voice_channel/v1/events.proto";
import "voice_channel/v1/requests.proto";

message GatewayEnvelope {
  oneof payload {
    VoiceChannelUserJoinedEvent user_joined_event = 1;
    VoiceChannelUserLeftEvent user_left_event = 2;
    VoiceChannelCreatedEvent created_event = 3;
    VoiceChannelDeletedEvent deleted_event = 4;
    BotVoiceChannelRenameEvent rename_event = 5;
  }
}

message ServiceEnvelope {
  oneof payload {
    CreateVoiceChannelRequest create_channel_request = 1;
    DeleteVoiceChannelRequest delete_channel_request = 2;
    RenameVoiceChannelRequest rename_channel_request = 3;
    BotVoiceChannelRenameCooldownExpiredEvent rename_cooldown_expired_event = 4;
  }
}