syntax = "proto3";

package voice_channel.v1;

message VoiceChannelUserJoinedEvent {
  int64 guild_id = 1;
  int64 user_id = 2;
  int64 channel_id = 3;
  optional int64 category_id = 4;
}

message VoiceChannelUserLeftEvent {
  int64 guild_id = 1;
  int64 user_id = 2;
  int64 channel_id = 3;
  optional int64 category_id = 4;
}

message VoiceChannelCreatedEvent {
  int64 guild_id = 1;
  int64 channel_id = 2;
  optional int64 category_id = 3;
  string name = 4;
}

message VoiceChannelDeletedEvent {
  int64 guild_id = 1;
  int64 channel_id = 2;
  optional int64 category_id = 3;
}

message BotVoiceChannelRenameEvent {
  int64 guild_id      = 1;
  int64 channel_id    = 2;
  string new_name     = 3;
}

message BotVoiceChannelRenameCooldownExpiredEvent {
  int64 guild_id      = 1;
  int64 channel_id    = 2;
}