"""Init voice-channel-service tables

Revision ID: b2c8534a0411
Revises:
Create Date: 2025-07-11 14:27:12.694044

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2c8534a0411"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS voice_channel")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("default_name_template", sa.String(), nullable=False),
        sa.Column(
            "available_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("guild_id"),
        schema="voice_channel",
    )
    op.create_table(
        "state",
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("active_users", sa.Integer(), nullable=False),
        sa.Column("pending_deletion", sa.Boolean(), nullable=False),
        sa.Column("last_rename_at", sa.DateTime(), nullable=True),
        sa.Column("rename_count", sa.Integer(), nullable=False),
        sa.Column("rename_window_start", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("channel_id"),
        schema="voice_channel",
    )
    op.create_index(
        "ix_vcs_guild_id", "state", ["guild_id"], unique=False, schema="voice_channel"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vcs_guild_id", table_name="state", schema="voice_channel")
    op.drop_table("state", schema="voice_channel")
    op.drop_table("config", schema="voice_channel")
    op.execute("DROP SCHEMA IF EXISTS voice_channel CASCADE")
    # ### end Alembic commands ###
